language: python

python:
  - "2.7"

#before_script:
#   - sudo apt-get update
        
install: 
        - sudo apt-get update
        - sudo apt-get install  maven ant  -y
        - pip install -r requirements.txt
        - sudo apt-get install ruby-dev rubygems ruby-bundler rake -y
        #install thrift building dependencies.
        - sudo apt-get install libboost-dev libboost-test-dev libboost-program-options-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev -y
        #install ruby 
        - \curl -sSL https://get.rvm.io | bash -s stable --ruby=2.1.0
        - source $HOME/.rvm/scripts/rvm
        - gem install thrift
        - gem install rspec
        - gem install thin
        - gem install bundler
        - ./build_thrift.sh


script: 
        - python setup.py test
        - python publishClients.py --local  --config thrift_medusa/config/travis-ci.yaml
