####            EDIT THIS FILE ####
#
#  Nothing in this file will do anything to production.  Break, modify it, 
#  copy it and tweak it as you see fit.  If you do merge in your changes try 
#  to make it quasi functional.  It relies mostly on localhost and local user 
#  having passwordless ssh access.  You should be able to run the entire 
#  verification process for prod + devel using this config file since it deploys
#  to /tmp via ssh.
#
#  Everything below is copy/paste from appConfig with modification to work locally.
thrift:
   ##TODO: Constraints Not yet supported
   constraints:
     enforce_empty: true   #fails if required empty is set to false.
     #visibilty_check: true #fails if changing a field from required to anything else
     #check_field_ordering: true
     #check_version_increment: true
   #needs fully qualified path of all support thrift compilers
   compilers:
      # if the same type of compiler is needed, then you should include
      # the version number in the name.  ie.  thrift_0_6_1  or finagle_0.5.0
      # whatever the 'name' is it will be used for the prefix in the artifact
      - name: thrift
        bin:  /usr/local/bin/thrift
        options: ""
        supported_languages: [java, ruby]
#      - name:  finagle
#        bin: /Developer/thrift/bin/thrift
#        options: ""
#        supported_languages: [java, ruby]
#      - name: scrooge
#        bin:  /dev/null
#        options: ""
#        supported_languages: [java]

   #constants found inside thrift files.
   thrift: src/main/thrift
   documentation:
     ##boolean denoting whether to generate / upload thrift documentation or not.
     doc_enabled: true
     ##generate documentation for --local mode.
     doc_local_enabled: true
     ##generate documentation for snapshot
     doc_snapshot: true
     doc_snapshot_postfix: -dev
     ##metal information about the local and remote host.
     documentation_server:
        user: sfaci
        host: localhost
        #absolute path
        remote_path: /home/sfaci/public_html/thriftdoc
        #relative path from your work directory
        local_path: doc

ruby:
   #sandbox is a directory relative to work/ where the .rb files generated by thrift are found.
   # default is gen-rb
   sandbox: gen-rb
   #
   ruby: ruby/lib
   snapshots: False
   destination: gemartifacts
   #prefix must be empty string or a value
   host: http://rubygems.corp.nextag.com:8808/
   ssh_host: localhost
   ssh_user: sfaci
   ssh_path: /tmp/gems
   author: Build Bot - Automated
   email: buildbot@wizecommerce.com
   scm: http://git.corp.nextag.com/?p=thrift/definitions.git;a=summary

java:
   include_source: true
   uber_jar: Yes
   #this is location where the thrift generate java files will be stored relative to work/ default is
   # gen-java
   sandbox: gen-java
   # this string denotes the prefix it should expect for dev version.
   # If using maven -SNAPSHOT is expected.
   dev_prefix: "-SNAPSHOT"
   java_host: http://crepo.corp.nextag.com/repo/components2/
   maven_dir: src/main/java
   maven_deploy_command: mvn install -DskipTests deploy:deploy
   maven_local_deploy: mvn install -DskipTests
   ##TODO: Run generated pom.xml through a beautifier
   poms:
     default:
        file: pom_template.xml
        maven_deployment: <distributionManagement> <repository> <id>crepodata.corp.nextag.com</id> <url>scp://sfaci@localhost/tmp/crepo</url> <uniqueVersion>true</uniqueVersion> </repository> </distributionManagement>
        maven_scm:  <scm> <connection>scm:git:git://git.corp.nextag.com/services/WIZEID.git</connection> <developerConnection>scm:git:ssh://kato@gerrit.corp.nextag.com:29418/services/WIZEID.git </developerConnection> <url>http://git@git.corp.nextag.com/services/WIZEID.git</url> <tag>${projectid}-${projectVersion}</tag> </scm>
        maven_repos:  <repositories> <repository> <id>nextag</id> <url>http://crepo.corp.nextag.com/repo/libraries/maven2</url> </repository> <repository> <id>nextag repo2</id> <url>http://crepo.corp.nextag.com/repo/components2</url> </repository> </repositories>
        maven_java_source:  <plugin> <groupId>org.apache.maven.plugins</groupId> <artifactId>maven-source-plugin</artifactId> <executions> <execution> <id>attach-sources</id> <goals> <goal>jar</goal> </goals> </execution> </executions> </plugin>
     #if maven_* are omitted then it will fallback on default values
     business_object:
        file: pom_business_object.xml
     service:
        file: pom_service.xml
     shaded:
        file: pom_shaded.xml
        maven_deployment:  <distributionManagement> <repository> <id>crepodata.corp.nextag.com</id> <url>scp://sfaci@localhost/tmp/samir</url> <uniqueVersion>true</uniqueVersion> </repository> </distributionManagement>


global:
  ##Conventions/metaData
  company_name: wizecommerce
  service_prefix: services
  object_prefix: bizobj
  enum_prefix: enum
  exception_prefix: exception
  group_id: com.wizecommerce.data
  ##Special version won't be released, but SNAPSHOT will be deployed
  special_version: 0.0.0
  #Modes defines the various modes of operations.  Usually these are synonymous to languages.
  languages:
    java: Yes
    ruby: No
  #when set to true will only run local install, and skip deployment.
  local_install: True
  service_override: null
  # defines the 'work' directory.  Consider this a transient directory since the content will most
  # likely be wiped on each execution.
  work_dir: work
  #Paths defines the location of the thrift files.  Ideally, your bizObjs and serviceObj will be in a
  #seperate directory.
  paths:
    business_object: thrift/business-objects
    service_object: thrift/services
